### ISSUE TITLE
Move code to src/BTC/TiddlyFlex

### ISSUE THREAD

**Issue by linonetwo** [BurningTreeC/TiddlyFlex#14]
Hi, if you move ./TiddlyFlex to ./src/TiddlyFlex (like https://github.com/tiddly-gittly/tiddlywiki-calendar/tree/master/src), I can help you release plugin json and publish to CPL, would you like it?

I can't do this in a PR, because moving folder will create lots of changes, which is hard to review.

**Comment by BurningTreeC** [comment]
Hi @linonetwo 
What are the requirements for CPL?

**Comment by linonetwo** [comment]
Use https://github.com/tiddly-gittly/tw5-plugin-packer in github action, and release json in release. I can help you with that part.

**Comment by linonetwo** [comment]
Sorry, seems you don't need to move the folder.

You can use https://github.com/tiddly-gittly/tw5-plugin-packer?tab=readme-ov-file#github-action-template-%E6%A8%A1%E6%9D%BF

with

```
      - uses: tiddly-gittly/tw5-plugin-packer@v0.0.10
        with:
            source: "TiddlyFlex"
            output: "output"
```
